# Use the official PostgreSQL image as the base image
FROM postgres:latest

# Set environment variables for PostgreSQL
ENV POSTGRES_USER "postgres"
ENV POSTGRES_PASSWORD "12341234"
ENV POSTGRES_DB "postgres"

# Copy the SQL script to the container
COPY init.sql /docker-entrypoint-initdb.d/

# Expose the default PostgreSQL port
EXPOSE 5432